---
  - hosts: all
    become: present
    gather_facts: yes
    tasks:
     -  name: installing apache2
        apt:
          name: apache2
          state: present
     -   name: installing tmux
         apt:
            name: tmux
            state: present
